spring.application.name=devassistai

# Ollama config
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.base-url=http://localhost:11434

# Disable JPA auto-configuration for now (no DB needed in Phase 1)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server
server.port=8080

server.error.include-message=always
spring.mvc.problemdetails.enabled=false