spring.application.name=devassistai

# Ollama config
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.base-url=http://localhost:11434

# Embedding model config
spring.ai.ollama.embedding.options.model=mxbai-embed-large

# Disable JPA auto-configuration for now (no DB needed in Phase 1)
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/devassist
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# PGVector config
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024

# Server
server.port=8080

server.error.include-message=always
spring.mvc.problemdetails.enabled=false